apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: StudioBarber
  annotations:
    kubernetes.io/ingress.class: "gce"  #balanceador de carga , hay que poner una ip reservada
    kubernetes.io/ingress.global-static-ip-name: "gce-ip-reservada"

spec:
  rules:
    - http:
        paths:
          - path: /        # permite la entrada de las peticiones https al microservicio api-gateway(servicio)
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80


# Al no tener ingressClassName (para el controlador) lo maneja GKE controller con la antoacion ingress.class
# cuando el cleinte hace una peticopn ejemplo /reservas o /xxx lo lleva siempre al api-gateway service en el purto 80