apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: studio-barber
  annotations:
    kubernetes.io/ingress.class: "gce"  #balanceador de carga , hay que poner una ip reservada
    kubernetes.io/ingress.regional-static-ip-name: "gce-ip-reservada"
    #aumentar el tiempo de espera para las respuestas
    ingress.gcp.kubernetes.io/read-timeout: "120"
    ingress.gcp.kubernetes.io/write-timeout: "120"

spec:
  rules:
    - http:
        paths:
          - path: /        # permite la entrada de las peticiones https al microservicio api-gateway(servicio)
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80


# Al no tener ingressClassName (para el controlador) lo maneja GKE controller con la antoacion ingress.class
# cuando el cleinte hace una peticopn ejemplo /reservas o /xxx lo lleva siempre al api-gateway service en el purto 80